### ISSUE TITLE
Support of the new csv file format (new DKB portal)

### ISSUE THREAD

**Issue by mfernau** [hamvocke/dkb2homebank#17]
Hello hamvocke,

are you willing to support the new csv format in the new future? 
The DKB is starting to switch over to a new website (modernized and all the things which nobody really needs ...) and now exports other formatted CSV files.

Greetings
Martin

**Comment by hamvocke** [comment]
Hey hey!

Yeah, I think it's absolutely reasonable to support their new CSV format in this script. I haven't even checked it out yet since I didn't take the time to check out their new website.

I'll look into this soon (it'll take a few days for sure before I can start) and will get back to you.

Thanks for getting this on my radar 👍

**Comment by Ablesius** [comment]
hi @hamvocke,

since I'm working with the raw csv files with pandas now, I'm already looking at the new format. I might be able to help here, too. Will check back with you! :)

**Comment by hamvocke** [comment]
This should be fixed with 1dba49c. Let me know if there are any problems.
