### ISSUE TITLE
File open encoding and date format

### ISSUE THREAD

**Issue by seldomU** [hamvocke/dkb2homebank#18]
First of all, thank you for sharing this script!

I had two issues. The DKB CSV I got uses  two-digits for the year, so I used %y in convert_date. I also opened the file with 'utf-8-sig', otherwise the file's first line would start with the BOM character, causing identify_account_type to fail. I'm unfamiliar with python, so maybe that one was on me. Hope this is useful.

**Comment by hamvocke** [comment]
Thanks for the feedback! I assume you downloaded your CSV file from the new banking portal, not the old one? What account type do you have (does it say "DKB Cash" or "Girokonto" in the UI)?

DKB seems to have changed quite a bit around their CSV export lately, and depending on the account type you've got and the portal you're using to download the CSV file, you might be getting mixed results.

You're totally correct, the new portal seems to generate CSV files with `utf-8-sig` encoding and the date format is slightly different. I tried to make those tweaks for the `--giro` flag and removed the entire auto-detection mechanism (since we can't reasonably maintain it with all these variations, really), hoping that this helps moving forward.

**Comment by seldomU** [comment]
It's a Girokonto and I did download it from their new portal. Thanks again for your work. I just got started using homebank and without your script I would probably have given up. It's wild to me that pulling my transactions is this hard, I would have expected them to provide an API and instead we get a CSV download with changing format.

**Comment by hamvocke** [comment]
Heads-up: with the latest commit, I removed the `--cash`, `--visa`, and `--giro` flags from the script. It should now be capable of automatically detecting the input CSV file and do the right thing out of the box.
