### ISSUE TITLE
New CSV header breaks current implementation

### ISSUE THREAD

**Issue by Ablesius** [hamvocke/dkb2homebank#5]
Hi Ham,

DKB has changed their format for the csv file. The old header looked like this:

```csv
"Kontonummer:";"DE00000000000000000000 / Alex";

"Von:";"01.01.2020";
"Bis:";"10.03.2020";
"Kontostand vom 10.03.2020:";"12,34 EUR";

"Buchungstag";"Wertstellung";"Buchungstext";"Auftraggeber / Begünstigter";"Verwendungszweck";"Kontonummer";"BLZ";"Betrag (EUR)";"Gläubiger-ID";"Mandatsreferenz";"Kundenreferenz";
```

And the new header:

```csv
"Kontonummer:";"DE33333333333333333333 / Alex";

"Von:";"01.01.2019";
"Bis:";"31.12.2019";
"Kontostand vom 31.12.2019:";"43,21 EUR";
"Freitextsuche (im Verwendungszweck und Empfängerdaten):";"";"im Verwendungszweck und Empfängerdaten";
"Betrag von:";"";"bis:";"";

"Buchungstag";"Wertstellung";"Buchungstext";"Auftraggeber / Begünstigter";"Verwendungszweck";"Kontonummer";"BLZ";"Betrag (EUR)";"Gläubiger-ID";"Mandatsreferenz";"Kundenreferenz";
```

I think the problem could be solved by skipping over the header part with `reader.next()` until we reach actual input lines. Right now, the script crashes here:

```
/usr/bin/python3.8 /usr/share/pycharm/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 44553 --file /home/alex/Development/dkb2homebank/dkb2homebank.py -c /home/alex/ownCloud/documents/Finanzen/CSV-Exports/cash-2019.csv
pydev debugger: process 4919 is connecting

Connected to pydev debugger (build 192.6817.19)
Traceback (most recent call last):
  File "/home/alex/Development/dkb2homebank/dkb2homebank.py", line 60, in convert_DKB_cash
    'date': convert_date(row["buchungstag"]),
  File "/home/alex/Development/dkb2homebank/dkb2homebank.py", line 105, in convert_date
    date = datetime.strptime(date_string, "%d.%m.%Y")
  File "/usr/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Buchungstag' does not match format '%d.%m.%Y'

Process finished with exit code 1
```

So `strptime` receives a string it can't convert to a date ("Buchungstag").

Another idea would be to put the strptime line in a try-except block, but I'm not sure this is a good solution. I think `next()` is rather the way to go. What do you think?

Best,
Alex

**Comment by hamvocke** [comment]
Alex, happy to see that you're back on this! I only use this script occasionally so I don't always catch those changes right away, so thanks so much for investigating!

The current script is trying to skip the CSV headers already and is using a pretty naive heuristic to find the actual transaction lines:

[This is what the script is currently doing:](https://github.com/hamvocke/dkb2homebank/blob/master/dkb2homebank.py#L93-L101)

```python
def transaction_lines(file):
    lines = file.readlines()
    i = 1
    for line in lines:
        if "Betrag" in line:
            return lines[i:]
        i = i + 1

    raise ValueError("Can't convert CSV file without header line")
```

This approach is working _okay_ but it's super naive and breaking with this change. It's iterating over each line in a .csv file and will skip lines until it finds a line that contains the word _Betrag_. Both, the Cash and the Visa CSV contain the word _Betrag_ in their transaction lines so this was a shortcut to use this function for both files.

Now the problem is that the new CSV format uses the word _Betrag_ in its headers, leading the script to falsely assume that it's arrived at the transaction lines.

The simplest solution that'd work for now would be to change the `transaction_lines()` function from stopping at a line containing the word _Betrag_ to stopping at a line containing the word _Wertstellung_ (as this seems to be another one that's present in both, Cash and Visa files, but not in the CSV header).

What do you think?

**Comment by Ablesius** [comment]
> The simplest solution that'd work for now would be to change the transaction_lines() function from stopping at a line containing the word Betrag to stopping at a line containing the word Wertstellung (as this seems to be another one that's present in both, Cash and Visa files, but not in the CSV header).

This is at least a hotfix solution we could do (I might even be able to do that myself later). But in the long run, it might make sense to look into `next()` and just throw away the first n lines that are not needed. To me that looks simpler for debugging. I'm not entirely sure though, maybe there's an even better way.

One way or another, we should add a comment to this section of the code to make it clear why this is being done. I didn't find it when I was trying to debug the code (I might not have looked hard enough, true), this would surely add a bit of clarity.

**Comment by Ablesius** [comment]
Another idea: maybe we search for a line containing actual numbers/dates before we try to process them, because the lines before can't contain relevant data.

**Comment by hamvocke** [comment]
> in the long run, it might make sense to look into next() and just throw away the first n lines that are not needed

That's pretty much what the `transaction_lines()` function is doing. It's iterating over the lines in a given CSV file until it finds the line that precedes the transaction lines and only returns the lines following that specific line.

I agree that a comment helps here, and the function name could need some tweaking, too (`find_transaction_lines()` or `skip_header_lines()` might be good alternatives).

**Comment by Ablesius** [comment]
#7
